fof(a,axiom,exists(X,CurrentWorld)=>exists(X,'f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(a,axiom,'f_~(p=>q)=>(q=>p)pred'(CurrentWorld)=>'f_~(p=>q)=>(q=>p)'(CurrentWorld)=CurrentWorld).
fof(a,axiom,'f_~(p=>q)=>(q=>p)pred'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(a,axiom,exists(X,CurrentWorld)=>exists(X,'f_p=>q'(CurrentWorld))).
fof(a,axiom,'f_p=>qpred'(CurrentWorld)=>'f_p=>q'(CurrentWorld)=CurrentWorld).
fof(a,axiom,'f_p=>qpred'('f_p=>q'(CurrentWorld))).
fof(a,axiom,exists(X,CurrentWorld)=>exists(X,'f_q=>p'(CurrentWorld))).
fof(a,axiom,'f_q=>ppred'(CurrentWorld)=>'f_q=>p'(CurrentWorld)=CurrentWorld).
fof(a,axiom,'f_q=>ppred'('f_q=>p'(CurrentWorld))).
fof(d,axiom,p(CurrentWorld)=>p('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,p(CurrentWorld)=>p('f_p=>q'(CurrentWorld))).
fof(d,axiom,p(CurrentWorld)=>p('f_q=>p'(CurrentWorld))).
fof(d,axiom,q(CurrentWorld)=>q('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,q(CurrentWorld)=>q('f_p=>q'(CurrentWorld))).
fof(d,axiom,q(CurrentWorld)=>q('f_q=>p'(CurrentWorld))).
fof(d,axiom,'f_q=>ppred'(CurrentWorld)=>'f_q=>ppred'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,'f_q=>ppred'(CurrentWorld)=>'f_q=>ppred'('f_p=>q'(CurrentWorld))).
fof(d,axiom,'f_q=>ppred'(CurrentWorld)=>'f_q=>ppred'('f_q=>p'(CurrentWorld))).
fof(d,axiom,'f_~(p=>q)=>(q=>p)pred'(CurrentWorld)=>'f_~(p=>q)=>(q=>p)pred'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,'f_~(p=>q)=>(q=>p)pred'(CurrentWorld)=>'f_~(p=>q)=>(q=>p)pred'('f_p=>q'(CurrentWorld))).
fof(d,axiom,'f_~(p=>q)=>(q=>p)pred'(CurrentWorld)=>'f_~(p=>q)=>(q=>p)pred'('f_q=>p'(CurrentWorld))).
fof(d,axiom,'f_p=>qpred'(CurrentWorld)=>'f_p=>qpred'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,'f_p=>qpred'(CurrentWorld)=>'f_p=>qpred'('f_p=>q'(CurrentWorld))).
fof(d,axiom,'f_p=>qpred'(CurrentWorld)=>'f_p=>qpred'('f_q=>p'(CurrentWorld))).
fof(d,axiom,'p'(CurrentWorld)=>'p'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,'p'(CurrentWorld)=>'p'('f_p=>q'(CurrentWorld))).
fof(d,axiom,'p'(CurrentWorld)=>'p'('f_q=>p'(CurrentWorld))).
fof(d,axiom,'~(p=>q)'(CurrentWorld)=>'~(p=>q)'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,'~(p=>q)'(CurrentWorld)=>'~(p=>q)'('f_p=>q'(CurrentWorld))).
fof(d,axiom,'~(p=>q)'(CurrentWorld)=>'~(p=>q)'('f_q=>p'(CurrentWorld))).
fof(d,axiom,'q'(CurrentWorld)=>'q'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,'q'(CurrentWorld)=>'q'('f_p=>q'(CurrentWorld))).
fof(d,axiom,'q'(CurrentWorld)=>'q'('f_q=>p'(CurrentWorld))).
fof(d,axiom,'p=>q'(CurrentWorld)=>'p=>q'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,'p=>q'(CurrentWorld)=>'p=>q'('f_p=>q'(CurrentWorld))).
fof(d,axiom,'p=>q'(CurrentWorld)=>'p=>q'('f_q=>p'(CurrentWorld))).
fof(d,axiom,'~(p=>q)=>(q=>p)'(CurrentWorld)=>'~(p=>q)=>(q=>p)'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,'~(p=>q)=>(q=>p)'(CurrentWorld)=>'~(p=>q)=>(q=>p)'('f_p=>q'(CurrentWorld))).
fof(d,axiom,'~(p=>q)=>(q=>p)'(CurrentWorld)=>'~(p=>q)=>(q=>p)'('f_q=>p'(CurrentWorld))).
fof(d,axiom,'q=>p'(CurrentWorld)=>'q=>p'('f_~(p=>q)=>(q=>p)'(CurrentWorld))).
fof(d,axiom,'q=>p'(CurrentWorld)=>'q=>p'('f_p=>q'(CurrentWorld))).
fof(d,axiom,'q=>p'(CurrentWorld)=>'q=>p'('f_q=>p'(CurrentWorld))).
fof(1,axiom,'p'(CurrentWorld)=>p(CurrentWorld)).
fof(1,axiom,q(CurrentWorld)=>'q'(CurrentWorld)).
fof(1,axiom,('p'('f_p=>q'(CurrentWorld))=>'q'('f_p=>q'(CurrentWorld)))=>'p=>q'(CurrentWorld)).
fof(1,axiom,('p=>q'(CurrentWorld)&'~(p=>q)'(CurrentWorld))=>$false).
fof(1,axiom,'q'(CurrentWorld)=>q(CurrentWorld)).
fof(1,axiom,p(CurrentWorld)=>'p'(CurrentWorld)).
fof(1,axiom,('q'('f_q=>p'(CurrentWorld))=>'p'('f_q=>p'(CurrentWorld)))=>'q=>p'(CurrentWorld)).
fof(1,axiom,('~(p=>q)'('f_~(p=>q)=>(q=>p)'(CurrentWorld))=>'q=>p'('f_~(p=>q)=>(q=>p)'(CurrentWorld)))=>'~(p=>q)=>(q=>p)'(CurrentWorld)).
fof(1,axiom,?[X]:exists(X,startworld)).
fof(goal,conjecture,'~(p=>q)=>(q=>p)'(startworld)).
